export default {
  CREATE_POST: "CREATE_POST",
  SET_ERROR: "SET_ERROR",
  CLEAN_ERROR: "CLEAN_ERROR",
  STORE_POSTS: "STORE_POSTS",
  SET_PICTURE_URL: "SET_PICTURE_URL",
  CLEAN_PICTURE_URL: "CLEAN_PICTURE_URL",
  SET_PICTURE_UPLOADING: "SET_PICTURE_UPLOADING",
  SET_POST_COUNT: "SET_POST_COUNT",
  CLEAR_POST_COUNT: "CLEAR_POST_COUNT",
};
